"""extend course table and add chapter table

Revision ID: 45679f2b31a9
Revises: 07f8a2d74e3d
Create Date: 2018-04-25 16:26:17.505968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45679f2b31a9'
down_revision = '07f8a2d74e3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter', sa.Column('course_id', sa.Integer(), nullable=True))
    op.add_column('chapter', sa.Column('description', sa.String(length=256), nullable=True))
    op.add_column('chapter', sa.Column('name', sa.String(length=128), nullable=False))
    op.add_column('chapter', sa.Column('vedio_duration', sa.String(length=24), nullable=True))
    op.add_column('chapter', sa.Column('vedio_url', sa.String(length=256), nullable=True))
    op.create_index(op.f('ix_chapter_name'), 'chapter', ['name'], unique=True)
    op.create_foreign_key(None, 'chapter', 'course', ['course_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chapter', type_='foreignkey')
    op.drop_index(op.f('ix_chapter_name'), table_name='chapter')
    op.drop_column('chapter', 'vedio_url')
    op.drop_column('chapter', 'vedio_duration')
    op.drop_column('chapter', 'name')
    op.drop_column('chapter', 'description')
    op.drop_column('chapter', 'course_id')
    # ### end Alembic commands ###
