"""add new values to User

Revision ID: 5f663c618bc8
Revises: 752408066911
Create Date: 2018-04-21 12:33:59.101127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f663c618bc8'
down_revision = '752408066911'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=64), nullable=False))
    op.add_column('user', sa.Column('job', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('password', sa.String(length=256), nullable=False))
    op.add_column('user', sa.Column('role', sa.SmallInteger(), nullable=True))
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_column('user', 'role')
    op.drop_column('user', 'password')
    op.drop_column('user', 'job')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
