"""add new table live

Revision ID: 92efc90d8323
Revises: 87e62f8e4acd
Create Date: 2018-05-09 16:16:19.596823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92efc90d8323'
down_revision = '87e62f8e4acd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('up_id', sa.Integer(), nullable=True),
    sa.Column('live_url', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['up_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_live_live_url'), 'live', ['live_url'], unique=True)
    op.create_index(op.f('ix_live_name'), 'live', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_live_name'), table_name='live')
    op.drop_index(op.f('ix_live_live_url'), table_name='live')
    op.drop_table('live')
    # ### end Alembic commands ###
